// Application unit harness. No browser, live DOM, screenshots or GPU is used.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.join(__dirname,'..'),core=fs.readFileSync(path.join(root,'src/core.js'),'utf8'),app=fs.readFileSync(path.join(root,'src/app.js'),'utf8');
let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;};
function boot(storage=new Map(),denyStorage=false,rendererFails=false){
  let now=0,raf=[],elements=new Map(),tools=new Map();
  class Element{
    constructor(id=''){this.id=id;this.dataset={};this.hidden=false;this.inert=false;this.style={};this.listeners={};this.attrs={};this.disabled=false;this.checked=false;this.type='';this.children=[];this._html='';const classes=new Set();this.classList={toggle:(c,on)=>{if(on===undefined)on=!classes.has(c);on?classes.add(c):classes.delete(c);},add:c=>classes.add(c),remove:c=>classes.delete(c),contains:c=>classes.has(c)};}
    set innerHTML(text){this._html=text;this.children=[];for(const m of text.matchAll(/<(button|input|select)\b([^>]*)>/g)){const e=new Element();e.tag=m[1];for(const a of m[2].matchAll(/([\w-]+)="([^"]*)"/g)){e.attrs[a[1]]=a[2];if(a[1].startsWith('data-'))e.dataset[a[1].slice(5)]=a[2];if(a[1]==='id'){e.id=a[2];elements.set(e.id,e);}if(a[1]==='type')e.type=a[2];}e.disabled=/\bdisabled\b/.test(m[2]);e.checked=/\bchecked\b/.test(m[2]);this.children.push(e);}}
    get innerHTML(){return this._html;}
    querySelectorAll(){return this.children.filter(e=>!e.disabled);}
    querySelector(){return this.querySelectorAll()[0]||null;}
    addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}
    fire(name,event={}){for(const fn of this.listeners[name]||[])fn({type:name,target:this,preventDefault(){},...event});}
    focus(){document.activeElement=this;}
    setAttribute(k,v){this.attrs[k]=v;}
    closest(selector){return selector==='button[data-action]'&&this.dataset.action?this:null;}
    append(e){this.children.push(e);}
    getBoundingClientRect(){return {left:0,top:0,width:110,height:110};}
    setPointerCapture(){}
  }
  const element=id=>{if(!elements.has(id))elements.set(id,new Element(id));return elements.get(id);};
  const document=new Element('document');document.hidden=false;document.body=new Element('body');document.getElementById=element;document.createElement=()=>new Element();document.querySelectorAll=()=>[element('stage0'),element('stage1'),element('stage2')];document.modelContext={registerTool:t=>tools.set(t.name,t)};
  const window=new Element('window'),mq={matches:false,addEventListener(){}};
  class Renderer{constructor(canvas){this.canvas=canvas;this.stats={mode:'mock',triangles:0};this.lost=rendererFails;this.fatal=rendererFails;this.ext={};this.gl=rendererFails?null:{};this.error=rendererFails?'test WebGL unavailable':null;}draw(){}addEvent(){}project(x,y,z){return {x,y:z,w:1};}}
  const sandbox={console,Math,Number,JSON,Set,Map,document,window,localStorage:{getItem:k=>{if(denyStorage)throw Error('blocked');return storage.get(k)||null;},setItem:(k,v)=>{if(denyStorage)throw Error('blocked');storage.set(k,v);}},performance:{now:()=>now},matchMedia:()=>mq,requestAnimationFrame:f=>raf.push(f),ShuboRender:{Renderer},AbortController};
  const ctx=vm.createContext(sandbox);vm.runInContext(core,ctx);vm.runInContext(app,ctx);
  const click=(action,value)=>{const btn=element('menuContent').children.find(e=>e.dataset.action===action&&(value===undefined||e.dataset.value===value));assert.ok(btn,`button ${action} ${value} exists`);element('menu').fire('click',{target:btn});};
  const frames=(n=1)=>{for(let i=0;i<n;i++){now+=1000/60;const pending=raf;raf=[];pending.forEach(f=>f(now));}};
  const data=()=>JSON.parse(storage.get('shubo.dive.v2'));
  return {ctx,document,window,element,click,frames,data,storage,tools,state:()=>ctx.SHUBO_DIVE.inspect(),key:(key,type='keydown')=>document.fire(type,{key,repeat:false}),change:(id,value)=>{const e=element(id);if(e.type==='checkbox')e.checked=value;else e.value=value;element('menu').fire('change',{target:e});}};
}
const h=boot();ok(h.state().screen==='home'&&h.state().paused,'starts in home, paused');h.click('settings');h.change('setAnimations',false);ok(h.data().settings.animations===false,'animation preference saved');ok(h.data().run===null,'settings do not save a preview as an active run');ok(h.document.body.classList.contains('motion-off'),'animation off state applied');h.click('back');h.click('start');ok(h.state().screen==='play'&&!h.state().paused,'start button begins game');h.frames(2);h.key('d');h.frames(60);h.key('d','keyup');h.element('pause').fire('click');const saved=h.data();ok(saved.run.player.x<-3&&saved.run.player.y===14,'keyboard input moves actual simulation');ok(h.state().paused&&h.state().screen==='pause','pause opens modal');const clock=saved.run.clock;h.frames(60);h.window.fire('pagehide');ok(h.data().run.clock===clock,'pause freezes simulation');h.click('resume');h.frames(30);h.document.hidden=true;h.document.fire('visibilitychange');ok(h.state().paused,'background tab pauses');const hideClock=h.data().run.clock;h.frames(120);ok(h.data().run.clock===hideClock,'hidden tab does not progress');
const reload=boot(h.storage);ok(reload.state().screen==='home'&&reload.state().paused,'restored run starts paused');reload.click('resume');reload.frames(1);ok(reload.state().status==='playing','saved run resumes');ok(reload.data().settings.animations===false,'saved animation preference survives reload');
ok(reload.tools.has('read_flight_status')&&reload.tools.has('pause_flight'),'WebMCP contracts register in mock context');ok(reload.tools.get('read_flight_status').execute({}).screen==='play','status contract reads current screen');reload.tools.get('pause_flight').execute({});ok(reload.state().screen==='pause','pause contract uses app action');assert.throws(()=>reload.tools.get('pause_flight').execute({bad:true}));checks++;
const C=reload.ctx.ShuboCore,g=new C.Game(941);g.status='upgrade';g.gate=true;g.stageKills=6;g.saved=3;g.rescue.forEach(r=>r.saved=true);
const stageStore=new Map([['shubo.dive.v2',JSON.stringify({version:2,profile:C.meta({credits:300}),settings:{},run:g.snapshot()})]]);
const stage=boot(stageStore);stage.click('resume');ok(stage.state().screen==='upgrade','saved intermission opens card selection');stage.click('perk','hull');ok(stage.state().sector===1&&stage.state().screen==='play','card selects and continues sector');ok(stage.data().run.player.maxHp===135,'chosen card affects simulation');stage.element('pause').fire('click');stage.click('home');stage.click('hangar');stage.click('buy','gun');ok(stage.data().profile.credits===260&&stage.data().profile.levels.gun===1,'upgrade spends credits once');ok(stage.data().run.levels.gun===0,'permanent upgrade only affects new sorties');stage.click('back');stage.click('restart-confirm');stage.click('start');ok(stage.data().run.levels.gun===1,'new run receives permanent upgrade');
const win=new C.Game(42);win.sector=2;win.setWorld();win.rescue.forEach(r=>r.saved=true);win.saved=9;win.stageKills=11;win.bossSpawned=true;win.bossDefeated=true;win.gate=true;win.player.x=win.exit.x;win.player.z=win.exit.z;win.player.y=win.exit.y;win.score=15000;
const finalStore=new Map([['shubo.dive.v2',JSON.stringify({version:2,profile:C.meta({}),settings:{},run:win.snapshot()})]]),finish=boot(finalStore);finish.click('resume');finish.frames(2);ok(finish.state().screen==='result'&&finish.state().status==='won','extraction opens result');const awarded=finish.data().profile.credits;ok(awarded>0&&finish.data().profile.wins===1&&finish.data().run.paid,'result awards once and saves');finish.click('hangar');finish.click('back');ok(finish.data().profile.credits===awarded&&finish.data().profile.wins===1,'returning to results does not award twice');const again=boot(finalStore);again.click('start');ok(again.data().profile.credits===awarded,'reloading and retrying keeps award exact');
const defeat=new C.Game(42);defeat.player.hp=1;defeat.player.shotCd=999;defeat.bullet(defeat.player.x,defeat.player.y,defeat.player.z,1,0,0,true,99,0);const loseStore=new Map([['shubo.dive.v2',JSON.stringify({version:2,profile:C.meta({}),settings:{},run:defeat.snapshot()})]]),loss=boot(loseStore);loss.click('resume');loss.frames(2);ok(loss.state().screen==='result'&&loss.state().status==='lost','loss result connected');loss.click('start');ok(loss.state().status==='playing'&&loss.data().run.player.hp===110,'retry starts a fresh healthy ship');
const bad=boot(new Map([['shubo.dive.v2','not json']]));ok(bad.state().screen==='home','corrupt save recovers to home');ok(bad.element('storageNote').hidden,'corruption is not misreported as unavailable storage');bad.click('start');ok(bad.data().run,'new run works after corrupt save');
const denied=boot(new Map(),true);denied.click('start');denied.frames(30);ok(denied.state().status==='playing'&&!denied.element('storageNote').hidden,'storage denied: playable with visible notice');
const controls=boot();controls.click('start');controls.frames(2);controls.key('w');controls.frames(60);controls.key('w','keyup');ok(controls.state().flight.y>16,'W climbs in application');controls.element('cruise').fire('click');controls.frames(120);ok(!controls.state().flight.cruise,'mobile hold button toggles actual cruise');const yhold=controls.state().flight.y;controls.frames(60);ok(Math.abs(controls.state().flight.y-yhold)<.01,'hold stops ship at actual height');controls.key('b');controls.key('b','keyup');controls.frames(1);ok(controls.state().flight.cruise,'B resumes forward flight');const yaw=controls.state().flight.yaw;controls.element('world').fire('pointerdown',{pointerId:1,clientX:100,clientY:100});controls.element('world').fire('pointermove',{pointerId:1,clientX:140,clientY:80});controls.frames(1);controls.element('world').fire('pointerup',{pointerId:1,clientX:140,clientY:80});ok(controls.state().flight.yaw!==yaw,'drag steers 3D ship');
const oldRun=new C.Game(22).snapshot();delete oldRun.spaceVersion;for(const k of ['y','vy','pitch','roll','cruise'])delete oldRun.player[k];const oldJSON=JSON.stringify({version:1,profile:C.meta({credits:111}),settings:{},run:oldRun}),oldStore=new Map([['shubo.dive.v1',oldJSON]]),legacy=boot(oldStore);legacy.click('resume');legacy.element('pause').fire('click');ok(legacy.data().version===2&&legacy.data().profile.credits===111,'old profile migrates to v2');ok(oldStore.get('shubo.dive.v1')===oldJSON,'old save preserved');
const unavailable=boot(new Map(),false,true);ok(!unavailable.element('renderError').hidden&&unavailable.state().paused,'WebGL failure is explicit and paused');unavailable.click('start');ok(unavailable.state().screen==='home'&&unavailable.storage.size===0,'unavailable renderer cannot start invisible combat');
const report={checks,scope:'Node application event harness with mocked elements and renderer. Not browser or WebMCP implementation validation.'};console.log(JSON.stringify(report,null,2));fs.writeFileSync(path.join(root,'docs/app-verification.json'),JSON.stringify(report,null,2)+'\n');
