'use strict';
const fs=require('node:fs');
const [oldPath,newPath,outPath=require('node:path').join(__dirname,'../docs/render-performance.json')]=process.argv.slice(2);
if(!oldPath||!newPath)throw new Error('Usage: node compare.cjs old.results.json new.results.json [comparison.json]');
const old=JSON.parse(fs.readFileSync(oldPath,'utf8')),next=JSON.parse(fs.readFileSync(newPath,'utf8'));
if(old.frozenCoreSha256!==next.frozenCoreSha256)throw new Error('Frozen core differs');
if(old.benchmarkSha256&&next.benchmarkSha256&&old.benchmarkSha256!==next.benchmarkSha256)throw new Error('Benchmark version differs');
for(const k of ['fixtureSeed','warmup','samples','iterations'])if(old.method[k]!==next.method[k])throw new Error(`Measurement setting differs: ${k}`);
const nextById=new Map(next.rows.map(r=>[r.caseId,r]));if(nextById.size!==old.rows.length)throw new Error('Case count differs');
const pct=(a,b)=>a===0?null:(b/a-1)*100;const median=a=>[...a].sort((x,y)=>x-y)[Math.floor(a.length/2)];
const rows=old.rows.map(a=>{const b=nextById.get(a.caseId);if(!b)throw new Error(`Missing ${a.caseId}`);if(JSON.stringify(a.pose)!==JSON.stringify(b.pose)||JSON.stringify(a.viewport)!==JSON.stringify(b.viewport))throw new Error(`Fixture mismatch ${a.caseId}`);return {caseId:a.caseId,quality:a.quality,profile:a.profile,sector:a.sector,submittedTriangles:{old:a.submitted.triangles,new:b.submitted.triangles,changePct:pct(a.submitted.triangles,b.submitted.triangles)},submittedInstances:{old:a.submitted.instances,new:b.submitted.instances,changePct:pct(a.submitted.instances,b.submitted.instances)},buildDynamicMedianMs:{old:a.buildDynamicMs.median,new:b.buildDynamicMs.median,changePct:pct(a.buildDynamicMs.median,b.buildDynamicMs.median)},bufferUploadBytes:{old:a.sinkCalls.bufferUploadBytes,new:b.sinkCalls.bufferUploadBytes,changePct:pct(a.sinkCalls.bufferUploadBytes,b.sinkCalls.bufferUploadBytes)}};});
const summary=[];for(const quality of ['low','balanced','high'])for(const profile of ['combat','limit-stress']){const rr=rows.filter(r=>r.quality===quality&&r.profile===profile);const sum=key=>{const a=rr.reduce((n,r)=>n+r[key].old,0),b=rr.reduce((n,r)=>n+r[key].new,0);return {oldMean:a/rr.length,newMean:b/rr.length,changePct:pct(a,b)};};summary.push({quality,profile,cases:rr.length,submittedTriangles:sum('submittedTriangles'),submittedInstances:sum('submittedInstances'),bufferUploadBytes:sum('bufferUploadBytes'),buildDynamicMedianMs:{oldMedian:median(rr.map(r=>r.buildDynamicMedianMs.old)),newMedian:median(rr.map(r=>r.buildDynamicMedianMs.new)),medianPairedChangePct:median(rr.map(r=>r.buildDynamicMedianMs.changePct))}});}
const result={benchmarkSha256:next.benchmarkSha256,baseline:'2010fee',coreSha256:next.frozenCoreSha256,method:next.method,host:{node:next.node,cpu:next.cpu,arch:next.arch},old:{path:oldPath,sha256:old.rendererSha256,node:old.node},new:{path:newPath,sha256:next.rendererSha256,node:next.node},measurement:'CPU code counts and Node buildDynamic times only; not GPU/FPS or visual QA',timingWarning:'Single paired run can be affected by JIT, GC, process order and host load. Deterministic counts are separate from noisy timings.',summary,rows};fs.writeFileSync(outPath,JSON.stringify(result,null,2));console.log(JSON.stringify({outPath,summary},null,2));
