const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const path=require('node:path'),root=path.join(__dirname,'..');
const context=vm.createContext({console,Float32Array,Math,Number,JSON,Set});
for(const file of ['core.js','renderer.js'])vm.runInContext(fs.readFileSync(path.join(root,'src',file),'utf8'),context,{filename:file});
const C=context.ShuboCore,R=context.ShuboRender;
let checks=0;function ok(value,message){assert.ok(value,message);checks++;}
const html=fs.readFileSync(path.join(root,'dist/index.html'),'utf8');
ok(!/<(?:script|link|img|iframe)[^>]+(?:src|href)=/i.test(html),'no external runtime assets');
ok(!/fetch\(|XMLHttpRequest|import\(/.test(html),'offline runtime');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
// Dynamic menu strings may repeat an ID across mutually exclusive screens.
const shell=fs.readFileSync(path.join(root,'src/shell.html'),'utf8'),shellIds=[...shell.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
ok(new Set(shellIds).size===shellIds.length,'unique static IDs');
for(const s of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(s[1]);
ok(!html.includes('/* INLINE_'),'all build placeholders replaced');
const meshCounts={};
for(const kind of R.TYPES){
  const m=R.mesh(kind);meshCounts[kind]=m.count/3;ok(m.p.length===m.n.length,'normal count');ok([...m.p,...m.n].every(Number.isFinite),'finite mesh');
  for(let i=0;i<m.p.length;i+=9){const u=[0,1,2].map(k=>m.p[i+3+k]-m.p[i+k]),v=[0,1,2].map(k=>m.p[i+6+k]-m.p[i+k]),face=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];ok(face.reduce((n,x,k)=>n+x*(kind==='ring'?m.n[i+k]:m.p[i+k]),0)>0,kind+' outward winding');const center=[0,1,2].map(k=>(m.p[i+k]+m.p[i+3+k]+m.p[i+6+k])/3),dot=center.reduce((v,x,k)=>v+x*m.n[i+k],0);ok(kind==='ring'||dot>0,`${kind} outward normal ${i/9}: ${dot}`);}
}
const budgets=[];
function validateBatch(b){let count=0,triangles=0;for(const [kind,data]of Object.entries(b)){ok(data.length%R.STRIDE===0,'instance stride');ok(data.every(Number.isFinite),'finite instances');for(let i=0;i<data.length;i+=R.STRIDE){ok(data.slice(i+3,i+6).every(n=>n>0),'positive scale');ok(Math.abs(Math.hypot(...data.slice(i+6,i+10))-1)<.001,'normalized quaternion');}count+=data.length/R.STRIDE;triangles+=data.length/R.STRIDE*meshCounts[kind];}return {count,triangles};}
for(let stage=0;stage<3;stage++){
  const batch=R.scenery(stage,941),stat=validateBatch(batch);ok(stat.triangles<220000,'bounded static geometry');budgets.push({stage,...stat});
  const game=new C.Game();game.sector=stage;game.setWorld();game.saved=9;game.gate=true;game.spawn(3);for(let i=0;i<11;i++)game.spawn(i%3);for(let i=0;i<96;i++)game.bullet(0,14,0,1,0,1,i%2===0);
  const renderer=Object.create(R.Renderer.prototype);renderer.effects=Array.from({length:24},()=>({type:'pulse',x:0,y:14,z:0,t:.25,life:.55,value:18}));renderer.buildDynamic(game,5,true);const dyn=validateBatch(renderer.dynamic);ok(dyn.triangles<100000,'bounded worst-case dynamic geometry');budgets.at(-1).worstDynamic=dyn;
}
const view=R.lookAt([0,10,20],[0,0,0]),proj=R.perspective(Math.PI/3,1,.2,200),vp=R.multiply(proj,view);ok([...vp].every(Number.isFinite),'camera finite');
const w=vp[15];ok(Math.abs(vp[12]/w)<1e-6&&Math.abs(vp[13]/w)<1e-6,'look target centered');
function finiteGame(g){
  ok(Number.isFinite(g.score)&&g.score>=0,'score valid');ok(g.player.hp>=0&&g.player.hp<=g.player.maxHp,'health valid');ok(Math.hypot(g.player.x,g.player.z)<=132&&g.player.y>=-34&&g.player.y<=72,'arena bounded');
  ok(g.enemies.length<=C.LIMITS.enemies&&g.bullets.length<=C.LIMITS.bullets&&g.drops.length<=C.LIMITS.drops,'entity caps');
  for(const list of [g.enemies,g.bullets,g.drops])ok(list.every(e=>Number.isFinite(e.x)&&Number.isFinite(e.y)&&Number.isFinite(e.z)),'finite moving entities');
}
const run=new C.Game(18);for(let i=0;i<30000&&run.status==='playing';i++){run.step(1/60,{brake:true});run.drain();if(i%60===0)finiteGame(run);}ok(run.status==='lost','unattended stationary play reaches defeat');
const shot=new C.Game(1);shot.spawnTimer=999;const enemy=shot.spawn(0);Object.assign(enemy,{x:0,y:14,z:50});const hp=enemy.hp;
for(let i=0;i<120;i++){shot.step(1/60,{brake:true});shot.drain();}ok(shot.kills>0||enemy.hp<hp,'forward auto-shot hits');
const pulse=new C.Game(2);pulse.spawnTimer=999;const e=pulse.spawn(0);Object.assign(e,{x:2,y:17,z:68});pulse.bullet(2,14,70,-1,0,0,true);pulse.step(.016,{pulse:true,brake:true});ok(pulse.kills===1,'pulse kills nearby enemy');ok(pulse.bullets.every(b=>!b.enemy),'pulse clears hostile projectiles');const cd=pulse.player.pulseCd;pulse.step(.016,{pulse:true,brake:true});ok(pulse.player.pulseCd<cd,'cooldown prevents repeated pulse');
const inv=new C.Game(3);inv.hurt(10);const damaged=inv.player.hp;inv.hurt(10);ok(inv.player.hp===damaged,'damage invulnerability');inv.step(.016,{boost:true});ok(inv.player.boostCd>0,'boost starts');
const rescued=new C.Game(6);rescued.spawnTimer=999;rescued.player.x=rescued.rescue[0].x;rescued.player.z=rescued.rescue[0].z;rescued.player.y=rescued.rescue[0].y;rescued.player.cruise=false;for(let i=0;i<80;i++)rescued.step(1/60);ok(rescued.saved===1&&rescued.score===350,'rescue counted once');
const blocked=new C.Game(6);blocked.spawnTimer=999;blocked.player.x=blocked.rescue[0].x;blocked.player.z=blocked.rescue[0].z;blocked.player.y=blocked.rescue[0].y;blocked.player.cruise=false;const guard=blocked.spawn(3);guard.x=blocked.player.x;guard.z=blocked.player.z;guard.y=blocked.player.y;guard.cd=999;blocked.player.shotCd=999;blocked.player.inv=999;for(let i=0;i<80;i++)blocked.step(1/60);ok(blocked.saved===0,'nearby enemies prevent rescue');
for(const source of [shot,pulse,run,rescued]){const original=source.snapshot(),restored=C.Game.restore(JSON.parse(JSON.stringify(original)));ok(restored,'valid save restores');ok(JSON.stringify(restored.snapshot())===JSON.stringify(original),'state round trip');}
for(const bad of [null,{}, {status:'playing',sector:99}, {...rescued.snapshot(),player:{...rescued.player,x:Infinity}}, {...rescued.snapshot(),enemies:Array(100).fill({})}])ok(C.Game.restore(bad)===null,'invalid saves rejected');
for(const key of Object.keys(rescued.snapshot())){const missing=rescued.snapshot();delete missing[key];ok(C.Game.restore(missing)===null,`missing save field safely rejected: ${key}`);}
ok(C.Game.restore({...rescued.snapshot(),status:'upgrade',sector:2})===null,'no upgrade after final sector');
const transition=new C.Game(7);transition.rescue.forEach(r=>r.saved=true);transition.saved=3;transition.stageKills=6;transition.step(.016);ok(transition.gate,'cleared goals open gate');transition.player.x=transition.exit.x;transition.player.z=transition.exit.z;transition.player.y=transition.exit.y;transition.step(.016);ok(transition.status==='upgrade','gate reaches upgrade');ok(!transition.choosePerk('fake'),'invalid perk rejected');ok(transition.choosePerk('hull')&&transition.sector===1&&transition.player.maxHp===135,'perk advances stage');ok(!transition.choosePerk('hull'),'perk cannot repeat');
const boss=new C.Game(8);boss.sector=2;boss.setWorld();boss.stageKills=11;boss.rescue.forEach(r=>r.saved=true);boss.saved=9;boss.step(.016);ok(boss.bossSpawned&&boss.enemies.some(e=>e.type===3),'boss spawned after objectives');const big=boss.enemies[0];boss.hit(big,big.maxHp*.55);boss.step(.016);ok(big.phase===2,'boss phase two');boss.hit(big,999);boss.step(.016);ok(boss.bossDefeated&&boss.gate,'boss defeat opens final gate');boss.player.x=boss.exit.x;boss.player.z=boss.exit.z;boss.player.y=boss.exit.y;boss.step(.016);ok(boss.status==='won','final extraction wins');const final=boss.snapshot();boss.step(1);ok(JSON.stringify(boss.snapshot())===JSON.stringify(final),'finished world does not progress');
const sameTick=new C.Game(4);sameTick.sector=2;sameTick.setWorld();sameTick.spawnTimer=999;sameTick.bossSpawned=true;sameTick.player.hp=1;sameTick.player.shotCd=999;const lastBoss=sameTick.spawn(3);lastBoss.hp=12;lastBoss.cd=999;lastBoss.x=0;lastBoss.y=18;lastBoss.z=-70;sameTick.bullet(0,18,-70,1,0,0,false,12,0);sameTick.bullet(sameTick.player.x,sameTick.player.y,sameTick.player.z,1,0,0,true,99,0);sameTick.step(.016);ok(sameTick.bossDefeated&&sameTick.player.hp===1&&sameTick.status==='playing','boss kill cancels same-tick hostile bullets');

// Full XYZ control, volume collision, camera and migration regression checks.
const flight=new C.Game(101);flight.spawnTimer=999;const startY=flight.player.y;for(let i=0;i<60;i++)flight.step(1/60,{pitch:1});ok(flight.player.y>startY+2,'pitch climbs in real simulation');for(let i=0;i<120;i++)flight.step(1/60,{pitch:-1});ok(flight.player.pitch<-.9,'pitch descends');const oldYaw=flight.player.yaw;flight.step(.1,{turn:1,brake:true});ok(flight.player.yaw!==oldYaw,'yaw turns while braking');flight.step(.1,{toggleCruise:true});ok(!flight.player.cruise,'hold toggle works once across substeps');for(let i=0;i<180;i++)flight.step(1/60,{brake:true});const holding={...flight.player};flight.step(.1,{brake:true});ok(C.dist(holding,flight.player)<.001,'braking holds XYZ position');
const volumes=new C.Game();volumes.spawnTimer=999;volumes.player.cruise=false;const behind=volumes.spawn(0);Object.assign(behind,{x:0,y:14,z:90});ok(volumes.target()===null,'behind enemies excluded from aiming');Object.assign(behind,{x:0,y:14,z:45});ok(volumes.target()===behind,'forward enemy acquired');behind.y=60;ok(volumes.target()===null,'target outside vertical cone excluded');
const vertical=new C.Game();vertical.spawnTimer=999;Object.assign(vertical.player,{x:vertical.rescue[0].x,z:vertical.rescue[0].z,y:vertical.rescue[0].y+20,cruise:false});for(let i=0;i<90;i++)vertical.step(1/60);ok(vertical.saved===0,'same XZ at different height cannot rescue');
const obstacle={x:0,y:0,z:0,sx:4,sy:2,sz:5,q:C.rotation(.5,.2,.1)};ok(C.inside({x:0,y:0,z:0},obstacle),'oriented volume contains center');ok(C.segmentObstacle({x:0,y:10,z:10},{x:0,y:10,z:-10},obstacle)===null,'flight above rice is clear');ok(C.segmentObstacle({x:0,y:0,z:10},{x:0,y:0,z:-10},obstacle)!==null,'rice blocks central flight ray');
const bulletVolume=new C.Game();bulletVolume.spawnTimer=999;bulletVolume.player.cruise=false;bulletVolume.player.shotCd=999;const upper=bulletVolume.spawn(0);Object.assign(upper,{x:0,y:35,z:70});bulletVolume.bullet(0,14,69,0,0,1,false,100,120);bulletVolume.step(1/60);ok(upper.hp===upper.maxHp,'projectile at other altitude cannot hit');
const first=new C.Game();first.spawnTimer=999;first.player.cruise=false;first.player.shotCd=999;first.obstacles=[{x:0,y:14,z:43,sx:2,sy:2,sz:2,q:C.rotation(0)}];const front=first.spawn(2);Object.assign(front,{x:0,y:14,z:48,cd:999});first.bullet(0,14,51,0,0,-1,false,100,600);first.step(1/60);ok(first.kills===1,'enemy before wall receives swept impact');
const rim=new C.Game();rim.spawnTimer=999;rim.player.cruise=false;rim.obstacles=[];const side=rim.spawn(2);Object.assign(side,{x:16,y:14,z:58,cd:999});for(let i=0;i<60;i++)rim.step(1/60,{brake:true});ok(rim.kills>0||side.hp<side.maxHp,'muzzle aims at the target on edge of firing cone');
for(const pitch of [-1.12,0,1.12])for(const yaw of [-Math.PI,-1,0,2]){const p={x:0,y:14,z:70,yaw,pitch},pose=R.cameraPose(p,[],false),f=C.forward(yaw,pitch),q=C.rotation(yaw,pitch);ok(pose.eye.every(Number.isFinite),'chase camera finite');ok(pose.eye.reduce((n,v,i)=>n+(v-[p.x,p.y,p.z][i])*f[i],0)<0,'camera behind ship');ok(C.rotate([0,0,1],q).every((v,i)=>Math.abs(v-f[i])<1e-6),'ship model orientation matches flight direction');}
for(const eye of [[0,10,0],[0,-10,0],[0,0,0]])ok([...R.lookAt(eye,[0,0,0])].every(Number.isFinite),'vertical and zero-length view finite');
const nearWall={x:0,y:15,z:74,sx:8,sy:8,sz:2,q:C.rotation(0)},pilot={x:0,y:14,z:70,yaw:Math.PI,pitch:0},cam=R.cameraPose(pilot,[nearWall]);ok(!C.inside({x:cam.eye[0],y:cam.eye[1],z:cam.eye[2]},nearWall,.6),'camera retracts before close rice wall');
for(const [width,height]of [[390,844],[320,568],[1440,900]]){const portrait=width<height,pose=R.cameraPose(pilot,[],portrait),renderer=Object.create(R.Renderer.prototype);renderer.width=width;renderer.height=height;renderer.vp=R.multiply(R.perspective((portrait?72:65)*Math.PI/180,width/height,.18,340),R.lookAt(pose.eye,pose.at));const a=renderer.project(-2.05,14,70),b=renderer.project(2.05,14,70);ok(Math.abs(a.x-b.x)<width*.42,'ship leaves a readable flight view at '+width+'px');}
const pores=R.poreTexture(64);ok(pores.data.length===64*64*4,'inline pore texture dimensions');ok(new Set(Array.from(pores.data).filter((_,i)=>i%4===0)).size>30,'pore texture contains relief');
const legacy=JSON.parse(JSON.stringify(rescued.snapshot()));delete legacy.spaceVersion;for(const k of ['y','vy','pitch','roll','cruise'])delete legacy.player[k];const migrated=C.Game.restore(legacy);ok(migrated&&migrated.saved===legacy.saved&&migrated.score===legacy.score,'old campaign progress migrates');ok(migrated.player.y===14&&migrated.player.z===70&&migrated.spaceVersion===2,'old planar position migrates to safe 3D entrance');ok(migrated.enemies.length===0&&migrated.bullets.length===0,'legacy flat entities cannot leak into 3D');
const stuck=new C.Game();stuck.sector=2;stuck.setWorld();stuck.bossSpawned=true;ok(C.Game.restore(stuck.snapshot())===null,'inconsistent boss state rejected');
const report={checks,bytes:Buffer.byteLength(html),meshTriangles:meshCounts,budgets,unattendedDefeatSeconds:Math.round(run.clock),scope:'Node XYZ simulation, geometry, camera mathematics and saves only; no browser, shader compilation, GPU or physical-device tests.'};
console.log(JSON.stringify(report,null,2));fs.writeFileSync(path.join(root,'docs','verification.json'),JSON.stringify(report,null,2)+'\n');
